apiVersion: v1
kind: Service
metadata:
  name: {{ include "ignite-service.fullname" . }}
  labels:
    {{- include "ignite-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.thinClients }}
      targetPort: {{ .Values.service.thinClients }}
      protocol: TCP
      name: thin-clients
  selector:
    app: ignite-pod
