apiVersion: v1
kind: Service
metadata:
  name: {{ include "ignite-server.fullname" . }}
  labels:
    {{- include "ignite-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.management }}
      targetPort: {{ .Values.service.management }}
      protocol: TCP
      name: management
  selector:
    {{- include "ignite-server.selectorLabels" . | nindent 4 }}
