# Default values for ignite-k8s-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ignite-service:
  serviceAccount:
    create: true
    name: ignite-sa
  fullnameOverride: "ignite-service"

ignite-server:
  replicaCount: 1
  image:
    repository: localhost:32000/ignite-server
    pullPolicy: Always
    tag: "latest"
  fullnameOverride: "ignite-server-node"
  serviceAccount:
    create: false
    name: ignite-sa

ignite-client:
  replicaCount: 1
  image:
    repository: localhost:32000/ignite-client
    pullPolicy: Always
    tag: "latest"
  fullnameOverride: "ignite-client-node"
  serviceAccount:
    create: false
    name: ignite-sa